server:
  port: 8080

spring:
  application:
    name: user_query_app

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: luicarod

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    cache: false
